version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mv_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Vinit@7521}
      MYSQL_DATABASE: ${DB_NAME:-multi_vendor_ecommerce}
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PASSWORD:-Vinit@7521} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      target: prod
    container_name: mv_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5600
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-multi_vendor_ecommerce}
      DB_USER: root
      DB_PASS: ${DB_ROOT_PASSWORD:-Vinit@7521}
      JWT_SECRET: ${JWT_SECRET:-devsecret}
    ports:
      - "5600:5600"

  adminer:
    image: adminer:4
    container_name: mv_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
    driver: local
